### ISSUE TITLE
yo chrome-extension not working

### ISSUE THREAD

**Issue by asimkt** [yeoman/generator-chrome-extension#112] opened 2015-06-22 06:23 UTC
"yo chrome-extension" throws following error. 

Error chrome-extension 

You don't seem to have a generator with the name chrome-extension installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 12 registered generators run yo with the `--help` option.

[My colleague got it work. My system seems to have the problem]

command "sudo npm install -g generator-chrome-extension" shows:
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
generator-chrome-extension@0.3.1 /home/azim/npm-global/lib/node_modules/generator-chrome-extension
└── yeoman-generator@0.18.10 (read-chunk@1.0.1, dargs@3.0.1, detect-conflict@1.0.0, yeoman-welcome@1.0.1, xdg-basedir@1.0.1, user-home@1.1.1, rimraf@2.4.0, class-extend@0.1.1, diff@1.4.0, text-table@0.2.0, mime@1.3.4, underscore.string@2.4.0, async@0.9.2, shelljs@0.3.0, lodash@2.4.2, cli-table@0.3.1, istextorbinary@1.0.2, cross-spawn@0.2.9, nopt@3.0.2, debug@2.2.0, mkdirp@0.5.1, sinon@1.15.3, chalk@1.0.0, through2@0.6.5, run-async@0.1.0, yeoman-assert@1.0.0, inquirer@0.8.5, cheerio@0.18.0, github-username@1.1.1, file-utils@0.2.2, glob@4.5.3, findup-sync@0.2.1, mem-fs-editor@1.2.3, yeoman-environment@1.2.5, gruntfile-editor@0.2.0, pretty-bytes@1.0.4, dateformat@1.0.11, download@3.3.0)

but command: "yo" shows

? 'Allo Azim! What would you like to do? (Use arrow keys)
  Run a generator
❯ Gulp Angular 
  Gulp Angular Subtask 
  ──────────────
  Update your generators 
  Install a generator 
  Find some help 
  Get me out of here!

**Comment by ragingwind** [comment] 2015-06-22 18:03
Try this instruction https://github.com/yeoman/yeoman/issues/1297

**Comment by arthurvr** [comment] 2015-06-30 08:18
I'm going to close this as we never got a response and I'm not able to reproduce. As you indicated yourself, it's more likely to be an issue with your local setup.

> My system seems to have the problem

Be sure that you're on the latest npm (and on the latest `yo`)

> sudo npm install -g generator-chrome-extension

Don't use sudo to install a generator. Actually [fix the issue](https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md) instead.

**Closed by arthurvr** 2015-06-30 08:18 UTC

**Comment by asimkt** [comment] 2015-09-01 12:51
Thanks
